# Generated by Django 4.1 on 2024-01-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='users/default_profile_picture.jpg', upload_to='users/'),
        ),
    ]
